### ISSUE TITLE
Recording Macro keys

### ISSUE THREAD

**Issue by SyntaxVoid** [K900/g710#2]
Hi, I'm not really sure how to contact you so I'll just message you here.

I'm running on Ubuntu and just finished installing your driver, although I can't figure out how to change the macro key actions.. After installing the driver, the G1-6 keys defaulted to something else (they don't just display 1,2,3,4,5,6 anymore, but G4 mutes my system for example) Also the instructions for getting the backlighting is a little big vague. Would you be able to help me out a bit?

Thanks

**Comment by K900** [comment]
There's really no support for recording macro keys per se. The driver I've got is really basic, but it maps G1-G6 to special keycodes, so you can then use xmacro or AutoKey or whatever else to bind them. The backlighting is configurable with the buttons on the keyboard, or with the sliders in g710tool.
